# Generated by Django 3.1.3 on 2020-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201203_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='listing_images'),
        ),
    ]
