# Generated by Django 3.1.3 on 2020-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
